# Generated by Django 5.0.1 on 2024-01-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_rating', models.IntegerField()),
                ('product_description', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
