# Generated by Django 5.0.1 on 2024-01-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsearch',
            name='product_image',
        ),
    ]
