# Generated by Django 5.0.1 on 2024-01-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_remove_productsearch_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsearch',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='productsearch',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='productsearch',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='productsearch',
            name='product_rating',
        ),
        migrations.AddField(
            model_name='productsearch',
            name='cost',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsearch',
            name='feel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productsearch',
            name='misleading_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsearch',
            name='not_similar_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsearch',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productsearch',
            name='suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsearch',
            name='transparency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productsearch',
            name='wrong_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
