# Generated by Django 5.0.1 on 2024-01-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_remove_productsearch_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsearch',
            old_name='cost',
            new_name='Cost',
        ),
        migrations.RenameField(
            model_name='productsearch',
            old_name='misleading_data',
            new_name='MisleadingData',
        ),
        migrations.RenameField(
            model_name='productsearch',
            old_name='not_similar_data',
            new_name='NotsimilarData',
        ),
        migrations.RenameField(
            model_name='productsearch',
            old_name='rating',
            new_name='Rating',
        ),
        migrations.RenameField(
            model_name='productsearch',
            old_name='suggestion',
            new_name='Suggestion',
        ),
        migrations.RenameField(
            model_name='productsearch',
            old_name='transparency',
            new_name='Transparency',
        ),
        migrations.RenameField(
            model_name='productsearch',
            old_name='wrong_data',
            new_name='WrongData',
        ),
    ]
