# Generated by Django 5.0.1 on 2024-01-12 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_rename_cost_productsearch_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsearch',
            name='CurrentDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
