# Generated by Django 5.0.1 on 2024-01-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_productsearch_currentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsearch',
            name='Product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
