# Generated by Django 5.0.1 on 2024-01-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_productsearch_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsearch',
            old_name='Product_name',
            new_name='name',
        ),
    ]
