# Generated by Django 5.0.1 on 2024-01-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_rename_product_name_productsearch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsearch',
            name='Cor_f',
            field=models.TextField(blank=True, null=True),
        ),
    ]
