# Generated by Django 5.0.1 on 2024-02-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_productsearch_cor_f'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
