# Generated by Django 5.0.1 on 2024-02-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_alter_blogmodel_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsearch',
            old_name='Cor_f',
            new_name='ecommerce_specs',
        ),
        migrations.AddField(
            model_name='productsearch',
            name='official_specs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
