# Generated by Django 5.0.1 on 2024-02-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0011_rename_cor_f_productsearch_ecommerce_specs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsearch',
            name='omitted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
